CREATE TABLE indexed_document
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relative_path      VARCHAR(1024)            NOT NULL UNIQUE,
    format             VARCHAR(255)             NOT NULL,
    content_hash       VARCHAR(64)              NOT NULL,
    source_modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    indexed_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    content            TEXT                     NOT NULL
);
CREATE TABLE note_chunk
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id     BIGINT  NOT NULL REFERENCES indexed_document (id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL,
    content         TEXT    NOT NULL,
    excluded        BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE conflict_review
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id      BIGINT                   NOT NULL REFERENCES note_chunk (id) ON DELETE CASCADE,
    status        VARCHAR(32)              NOT NULL,
    conflict_type VARCHAR(255)             NOT NULL,
    confidence    INTEGER                  NOT NULL,
    rationale     TEXT                     NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE quiz
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(255)             NOT NULL,
    difficulty         VARCHAR(32)              NOT NULL,
    question_type      VARCHAR(32)              NOT NULL,
    time_limit_minutes INTEGER,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE quiz_question
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id                     BIGINT  NOT NULL REFERENCES quiz (id) ON DELETE CASCADE,
    position                    INTEGER NOT NULL,
    prompt                      TEXT    NOT NULL,
    explanation                 TEXT    NOT NULL,
    additional_learning_context TEXT
);
CREATE TABLE quiz_question_options
(
    quiz_question_id BIGINT NOT NULL REFERENCES quiz_question (id) ON DELETE CASCADE,
    options          VARCHAR(255)
);
CREATE TABLE quiz_question_correct_option_indexes
(
    quiz_question_id       BIGINT NOT NULL REFERENCES quiz_question (id) ON DELETE CASCADE,
    correct_option_indexes INTEGER
);
CREATE TABLE quiz_question_citations
(
    quiz_question_id BIGINT NOT NULL REFERENCES quiz_question (id) ON DELETE CASCADE,
    citations        VARCHAR(255)
);
CREATE TABLE quiz_attempt
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id               BIGINT                   NOT NULL REFERENCES quiz (id) ON DELETE CASCADE,
    submitted_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    score                 INTEGER                  NOT NULL,
    possible_score        INTEGER                  NOT NULL,
    selected_answers_json TEXT                     NOT NULL
);
