CREATE TABLE app_session
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at                 TIMESTAMP WITH TIME ZONE,
    input_tokens             BIGINT                   NOT NULL DEFAULT 0,
    output_tokens            BIGINT                   NOT NULL DEFAULT 0,
    total_tokens             BIGINT                   NOT NULL DEFAULT 0
);

CREATE TABLE session_activity
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id               BIGINT                   NOT NULL REFERENCES app_session (id) ON DELETE CASCADE,
    activity_type            VARCHAR(32)              NOT NULL,
    status                   VARCHAR(32)              NOT NULL,
    description              VARCHAR(1024)            NOT NULL,
    started_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at             TIMESTAMP WITH TIME ZONE,
    input_tokens             BIGINT                   NOT NULL DEFAULT 0,
    output_tokens            BIGINT                   NOT NULL DEFAULT 0,
    total_tokens             BIGINT                   NOT NULL DEFAULT 0
);

CREATE INDEX idx_app_session_started_at ON app_session (started_at DESC);
CREATE INDEX idx_session_activity_session_started ON session_activity (session_id, started_at);
